### ISSUE TITLE
NN can only be initialized from spec, not from NN object

### ISSUE THREAD

**Issue by erniejunior** [YARL-project/YARL#2]
Watch out! Your documentation says, that I can feed a NeuralNetwork object into the agent. But that is not true with the current implementation. Relevant code section:
https://github.com/YARL-project/YARL/blob/bc2e65a5f4430629d0558b23d45edd1029d42178/yarl/agents/agent.py#L97

**Comment by sven1977** [comment]
It should work via the Specifiable.from_spec method (if network_spec is already an instance of the NeuralNetwork class, it should return it as is).
What is the error message you are getting?

**Comment by erniejunior** [comment]
Nevermind then.
